### ISSUE TITLE
LatexView won't work

### ISSUE THREAD

**Issue by mcooganj** [LaTeX-Box-Team/LaTeX-Box#100]
I have just installed Latex-Box, which is running with MacVim.  To take advantage of the dynamic linking with Skim, i installed skim 1.4.3. 

The :LatexView command does not seem to work.  :Latexmk works fine and generates the pdfs, but i am not able to launch a viewer (which is annoying). 

To test macvim and skim, i tried the following -- which works:

`:!open -a Skim pdfTest.pdf` 

setting `let g:LatexBox_latexmk_options = '-pv'` and commenting out `let g:LatexBox_viewer = 'Skim'` means that `\ll` throws the pdf via preview, however it'd be nice to link to Skim. Also, even with this hack, :LatexView does not work. 

What am i missing? 

thanks in advance

mj

**Comment by belmarca** [comment]
@msto Right-click a PDF file, go to Get Info and then to the Open With tab, choose Skim app and then press Change All. Worked for me.
