### ISSUE TITLE
Unknown function: uniq

### ISSUE THREAD

**Issue by sappjw** [LaTeX-Box-Team/LaTeX-Box#190]
9ddd65086820d96df1cef143 seems to have broken this plugin for me.  I get the error below when compiling a LaTeX file that generates warnings:

> Error detected while processing function LatexBox_Latexmk..LatexBox_LatexErrors..<SNR>52_log_contains_error:
line    3:
E117: Unknown function: uniq
E15: Invalid expression: uniq(map(lines, 'matchstr(v:val, ''^.*\ze:\d\+:'')'))
Compiling to pdf ... there were warnings!

This error goes away after reverting 9ddd65086820d96df1cef143.

Version info (current stable on Fedora 20):
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 15 2014 12:08:26)
Included patches: 1-179

**Comment by guyru** [comment]
I made a [pull request](https://github.com/LaTeX-Box-Team/LaTeX-Box/pull/223) with a patch that I believe fixes this issue (at least for me it did).
