### ISSUE TITLE
Latex-Box won't compile LaTeX on OS X Yosemite

### ISSUE THREAD

**Issue by felixjung** [LaTeX-Box-Team/LaTeX-Box#210]
Hi,

Today I tried to compile a LaTeX document on OS X Yosemite Developer Release 7 for the first time. I ran into some issues...
After triggering compilation usually my PDF viewer pops up. This time it did not. However, LaTeX-Box did not report any problems. Looking at the error log (local leader + le) it did not show any errors either.
I deleted all LaTeX garbage from the folder and tried again. Nothing would happen. Manually triggering the error window gave me this:
![screen shot 2014-09-06 at 23 42 14](https://cloud.githubusercontent.com/assets/265947/4176664/1a73ace0-360f-11e4-8868-6f968759e6b3.png)

I can compile my document using latexmk from terminal just fine. Texshop also works. Is this something you could look into?

Thanks!

**Comment by johannes-darms** [comment]
I'm running OS X 10.10.4 using vim in Terminal and get the same error with the current master and latest vim (7.4.826) and latex-mk version 2.1. Compiling using the terminal is fine, just latex-box is producing this error. Has someone solved this issue?

`Compiling to pdf ... (async off!)
Error detected while processing function LatexBox_Latexmk..LatexBox_LatexErrors:
line   16:
E40: Can't open errorfile /Users/johannesdarms/####/####.log
Error detected while processing function LatexBox_Latexmk:
line  210:
E171: Missing :endif`

**Comment by stsievert** [comment]
I'm running Vim 7.4 with patch 769 via `brew install macvim`, latexmk version 4.39 and the most recent version of LaTeX-Box installed with vim-plug. I can compile just fine from GUI and terminal vim.

(Also running OSX 10.10.4).

**Comment by johannes-darms** [comment]
@scottsievert : Thanks for your feedback. 
I updated to a newer version of latexmk ( with tlgmr) which solved the problem. The version I used previously is the one from sf, thought that would be the project site...
