### ISSUE TITLE
error in ReadTOC function in certain cases

### ISSUE THREAD

**Issue by ThomasFeher** [LaTeX-Box-Team/LaTeX-Box#227]
Given this minimal example:

    \documentclass{book}
    \begin{document}
    
    \section{test1}
    \subsection{test2}
    \subsubsection{{\sc test}3}
    
    \end{document}

running `:LatexTOC` gives an Error in ReadTOC at line 55, which is:

    len(tree) > 1 && tree[0] =~ '^\\\(numberline\|tocsection\)'

The TOC is opened correctly and everything works fine. Its just an annoyance to press return everytime.

**Comment by lervag** [comment]
Fixed by #228.
