### ISSUE TITLE
Citation complete in files added with \input

### ISSUE THREAD

**Issue by calenwalshe** [LaTeX-Box-Team/LaTeX-Box#231]
Is it possible to use citation complete within documents that are being included in the compile via \input?

**Comment by lervag** [comment]
Yes, I think it should be possible.

**Comment by calenwalshe** [comment]
Tried a few things and the following ended up working. Changing the filetype to .tex resulted in autocomplete asking for the location of the main latex file. Once specified autocomplete functions normally.

**Comment by ThomasFeher** [comment]
@calenwalshe: from the LaTeX-Box FAQ:
Q: How can I specify the main TeX file for a multi-file document

A: There are several ways to do this:

   1. Add a comment to the first few lines of your file to specify this: >
        %! TEX root = main.tex
<  2. Create an empty file called 'main.tex.latexmain' in the same directory.
