### ISSUE TITLE
"g:LatexBox_build_dir" does not take any effect on latexmk command

### ISSUE THREAD

**Issue by dynosure** [LaTeX-Box-Team/LaTeX-Box#83]
When I have `let g:LatexBox_build_dir="build"` in my .vimrc and run latexmk using `\ll`, output files are in the TeX root directory.

In order to get everything work, I have to add `-outdir=build` in "g:LatexBox_latexmk_options" making it `let g:LatexBox_latexmk_options="-outdir=build -pvc"`.

It is normal as no **g:LatexBox_build_dir** related code was found in **latexmk.vim**. I am not sure if it is developed to be like this or did I miss anything here.

BTW, thanks for making this great vim plugin.

**Comment by dailylama** [comment]
Is it going to be fixed? I've read your answer dating back to 2013 about you using .latexmkrc, and about you personally don't want want to fix it

**Comment by lervag** [comment]
If by "you" you are referring to me: I don't use LaTeX-Box. I would recommend you instead try [vimtex](https://github.com/lervag/vimtex/).

**Comment by dailylama** [comment]
traded bad for worse;
