### ISSUE TITLE
Setting pdflatex option through g:LatexBox_latexmk_options

### ISSUE THREAD

**Issue by michamos** [LaTeX-Box-Team/LaTeX-Box#95]
Hi,

I would like to use SyncTeX, and this requires to pass the option `-synctex=1` to PDFLaTeX.
In the docs, the recommended way is to add an appropriate line to the `.latexmkrc` file.
I would like to avoid having extra files if possible, and I figured out that it is possible to pass the option to latexmk through `g:LatexBox_latexmk_options`. The required setting is

```
let g:LatexBox_latexmk_options="-pdflatex='pdflatex -synctex=1 \\%O \\%S'"
```

The amount of escaping needed in order for vim not to expand the `%` is non-obvious and was found by trial and error. Maybe it is possible to make vim escape the `%` when this variable is used, but I don't know how.
Otherwise, it would probably be good to document this option in the FAQ, as an alternative to the `.latexmkrc` way.

**Comment by salviati6** [comment]
I'm sorry to report that even after the fix, neither

> let g:LatexBox_latexmk_options="-pdflatex='pdflatex -synctex=1 \\\\%O \\\\%S'"

nor

> let g:LatexBox_latexmk_options="-pdflatex='pdflatex -synctex=1 \%O \%S'"

works on my Windows machine.

I turned to TeXstudio and found that its preset is

> latexmk -pdf -silent -pdflatex="pdflatex -synctex=1 %%O %%S" %

so I changed the configuration in my .vimrc to

>let g:LatexBox_latexmk_options="-pdflatex='pdflatex -synctex=1 %%O %%S'"

and it finally works. Maybe the docs need an update?

Environment: Windows 7 SP1 64-bit, VIM 7.4.589 64-bit, latest version of LaTeX-Box with SumatraPDF
